### PR TITLE
Add bangle.io

### PR DESCRIPTION
**Pull request by kepta**
https://bangle.io is a simple yet powerful note taking web app that does not have any servers and does not take users that as hostage. It relies on [native file storage api](https://web.dev/file-system-access/ ) to read and modify your locally saved markdown notes.

### CODE REVIEW

**Comment by rosano** [comment]
This doesn't run for me and I'm using Safari 12 on macOS or Safari on iOS 13.

Screen Shot 2021-05-27 at 12 07 22

I'm not sure what the issue is exactly but you might want to try modifying your build/compile settings to avoid using newer JavaScript syntax.

Would be great someday to also sync with [remoteStorage](https://remotestorage.io) or [Fission](https://guide.fission.codes/developers/webnative).

**Comment by kepta** [comment]
Hey sorry for the trouble, I have updated the app. With my limited access to this version via BrowserStack I was able to open the app. Do you want to check if it works now?

**Comment by rosano** [comment]
Works! Thank you and congrats on the app, it looks super slick.

**Comment by rosano** [comment]
Feel free to join https://github.com/0dataapp/small-web-app-ring by placing a link somewhere on the site and then making a pull request.

**Comment by kepta** [comment]
@rosano I was hoping that this would lead to https://0data.app show bangle.io, but it currently isn't. Is there a separate place to add things to that website?

**Comment by rosano** [comment]
i'm currently hosting it statically so as soon as i update it will grab the latest data

**Pull request merged**
